Bot/src/objects/UserBotMessage__c.object
<CustomObject>
    <description>The record to be saved when the user submits a message</description>
    <fields>
        <fullName>ContentDocumentId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The id of the attached file</description>
        <label>ContentDocumentId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message entered in the input</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>UserBotMessage</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserBotMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot/src/classes/AttachmentTest.cls
@IsTest
public class AttachmentTest {
	
    @IsTest
    public static void testGetAttachmentDetails(){
        BotResponse response = BotController.submitWithAttachment('Message', null, 'url', 'fileName.png', 'content');
        
        UserBotMessage__c message = [Select Id, ContentDocumentId__c, Message__c From UserBotMessage__c Limit 1];
        String messageId = message.id;
        AttachmentController.AttachmentDetails details = AttachmentController.attachmentDetails(messageId);
        
        System.assert(details != null);
        System.assert(details.contentDocumentId != '');
        
    }
    
    @IsTest
    public static void testGetAttachmentDetailsIncorrectId(){
        BotResponse response = BotController.submitWithAttachment('Message', null, 'url', 'fileName.png', 'content');
        
        UserBotMessage__c message = [Select Id, ContentDocumentId__c, Message__c From UserBotMessage__c Limit 1];
        ContentVersion ctv = [Select id from ContentVersion Limit 1];
        
        String messageId = ctv.Id;
        AttachmentController.AttachmentDetails details = AttachmentController.attachmentDetails(messageId);
        
        System.assert(details == null);
    }
}