Bot/src/objects/UserBotMessage__c.object
<CustomObject>
    <description>The record to be saved when the user submits a message</description>
    <fields>
        <fullName>ContentDocumentId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The id of the attached file</description>
        <label>ContentDocumentId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>UserBotMessage</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserBotMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot/src/classes/AttachmentController.cls
public class AttachmentController {
    
    public class AttachmentDetails{
        @AuraEnabled 
        public string contentDocumentId {get; set;}
        @AuraEnabled
        public string contentVersionId {get; set;}
    }
    
    @AuraEnabled
    public static AttachmentDetails attachmentDetails(Id messageId){
        AttachmentDetails result = null;
        //TBD: Field level security
        try{
            UserBotMessage__c message = [SELECT id, ContentDocumentId__c From UserBotMessage__c where Id = :messageId];
            if(!String.isBlank(message.ContentDocumentId__c)){
                result = new AttachmentDetails();
                ContentDocument document = [Select id, LatestPublishedVersionId From ContentDocument where Id = :message.ContentDocumentId__c];
                result.contentDocumentId = document.Id;
                result.contentVersionId = document.LatestPublishedVersionId;
            }
        }catch(Exception e){
            result = null;
        }
            
        return result;
    }
    
}