Bot_V2/src/objects/Bot_Notification__e.object
<CustomObject>
    <fields>
        <fullName>Known_Issue_Subscriber__c</fullName>
        <label>Known_Issue_Subscriber</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Bot Notification</label>
    <pluralLabel>Bot Notifications</pluralLabel>
</CustomObject>

Bot_V2/src/objects/Einstein_Data_Message__c.object
<CustomObject>
    <fields>
        <fullName>Einstein_Keyword__c</fullName>
        <label>Einstein Keyword</label>
        <referenceTo>Einstein_Keyword__c</referenceTo>
        <relationshipLabel>Einstein Data Messages</relationshipLabel>
        <relationshipName>Einstein_Data_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Known_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Known Issue</label>
        <referenceTo>Known_Issue__c</referenceTo>
        <relationshipLabel>Einstein Data Messages</relationshipLabel>
        <relationshipName>Einstein_Data_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <label>Einstein Data Message</label>
    <nameField>
        <displayFormat>EDM-{0000}</displayFormat>
        <label>Einstein Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Einstein Data Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bot_V2/src/objects/Einstein_Keyword__c.object
<CustomObject>
    <label>Einstein Keyword</label>
    <nameField>
        <label>Einstein Keyword Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Keywords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot_V2/src/objects/Known_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Dashboard_Report_Id__c</fullName>
        <label>Dashboard/Report Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Id__c</fullName>
        <label>Document Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Einstein_Keyword__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einstein Keyword</label>
        <referenceTo>Einstein_Keyword__c</referenceTo>
        <relationshipLabel>Known Issues</relationshipLabel>
        <relationshipName>Known_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Template_Id__c</fullName>
        <label>Email Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Due_Date__c</fullName>
        <label>Estimated Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Message_Summary__c</fullName>
        <inlineHelpText>The message simplified by the Admin.</inlineHelpText>
        <label>Message Summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>The message as provided by the user.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_List_ObjectName__c</fullName>
        <label>Object List ObjectName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Highest (1)</fullName>
                </value>
                <value>
                    <fullName>High (2)</fullName>
                </value>
                <value>
                    <fullName>Normal (3)</fullName>
                </value>
                <value>
                    <fullName>Low (4)</fullName>
                </value>
                <value>
                    <fullName>Lowest (5)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_Detail_Id__c</fullName>
        <label>Record Detail Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Issue</label>
        <referenceTo>Known_Issue__c</referenceTo>
        <relationshipLabel>Related Issues</relationshipLabel>
        <relationshipName>Related_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Duplicated</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visualforce_Page_Name__c</fullName>
        <label>Visualforce Page Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
  
    <label>Known Issue</label>
    <nameField>
        <displayFormat>KI-{0000}</displayFormat>
        <label>Known Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Issues</pluralLabel>
    <recordTypes>
        <fullName>Documents</fullName>
        <active>true</active>
        <label>Documents</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <recordTypes>
        <fullName>Package</fullName>
        <active>true</active>
        <label>Package</label>
    </recordTypes>
    <recordTypes>
        <fullName>Unknown</fullName>
        <active>true</active>
        <label>Unknown</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot_V2/src/objects/Known_Issue_Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Known_Issue__c</fullName>
        <label>Known Issue</label>
        <referenceTo>Known_Issue__c</referenceTo>
        <relationshipLabel>Known Issue Subscribers</relationshipLabel>
        <relationshipName>Known_Issue_Subscribers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriber</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Known_Issue_Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Known Issue Subscriber</label>
    <nameField>
        <label>Known Issue Subscriber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Known Issue Subscribers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bot_V2/src/classes/KnownIssuesUtils.cls
public class KnownIssuesUtils {

    public static final String STATUS_NEW = 'New';
    public static final String STATUS_PENDINGAPPROVAL = 'Pending Approval';
    public static final String STATUS_FIXED = 'Fixed';
    public static final String STATUS_DUPLICATED = 'Duplicated';
    public static final String STATUS_INVALID = 'Invalid';

    private static final Map<String, Schema.RecordTypeInfo> KI_RECORDTYPES = Schema.SObjectType.Known_Issue__c.getRecordTypeInfosByName();
    public static final String RTYPE_NAME_DR = 'Dashboard & Report';
    public static final String RTYPE_NAME_DOC = 'Documents';
    public static final String RTYPE_NAME_ET = 'Email Template';
    public static final String RTYPE_NAME_OL = 'Object List';
    public static final String RTYPE_NAME_OTHER = 'Other';
    public static final String RTYPE_NAME_PKG = 'Package';
    public static final String RTYPE_NAME_RD = 'Record Detail';
    public static final String RTYPE_NAME_UNK = 'Unknown';
    public static final String RTYPE_NAME_VFP = 'Visualforce Pages';
    public static final Id RTYPE_ID_DR = KI_RECORDTYPES.get(RTYPE_NAME_DR).getRecordTypeId();
    public static final Id RTYPE_ID_DOC = KI_RECORDTYPES.get(RTYPE_NAME_DOC).getRecordTypeId();
    public static final Id RTYPE_ID_ET = KI_RECORDTYPES.get(RTYPE_NAME_ET).getRecordTypeId();
    public static final Id RTYPE_ID_OL = KI_RECORDTYPES.get(RTYPE_NAME_OL).getRecordTypeId();
    public static final Id RTYPE_ID_OTHER = KI_RECORDTYPES.get(RTYPE_NAME_OTHER).getRecordTypeId();
    public static final Id RTYPE_ID_PKG = KI_RECORDTYPES.get(RTYPE_NAME_PKG).getRecordTypeId();
    public static final Id RTYPE_ID_RD = KI_RECORDTYPES.get(RTYPE_NAME_RD).getRecordTypeId();
    public static final Id RTYPE_ID_UNK = KI_RECORDTYPES.get(RTYPE_NAME_UNK).getRecordTypeId();
    public static final Id RTYPE_ID_VFP = KI_RECORDTYPES.get(RTYPE_NAME_VFP).getRecordTypeId();


    // To be used by the BOT to know the count of Known Issues on a page
    @AuraEnabled
    public static Integer getKnownIssuesCount(Id recordTypeId, String targetName, String targetId) {
        return getKnownIssues(recordTypeId, targetName, targetId).size();
    }

    public static Known_Issue__c createKnownIssue(Id dataMessageId, String currentUrl, ContentVersion contentVersion){

        List<Einstein_Data_Message__c> edm = [SELECT Id, Message__c FROM Einstein_Data_Message__c WHERE Id = :dataMessageId];

        String sObjectTypeName = '';
        Id sObjectId = null;

        if(currentUrl.contains('sObject')){
            String checkId = currentUrl.substringBetween('/sObject/', '/');

            if((checkId.length()==15 || checkId.length()==18) && Pattern.matches('^[a-zA-Z0-9]*$', checkId)){
                sObjectId = checkId;
            }else{
                sObjectTypeName = checkId;
            }

        }

        if(!String.isBlank(sObjectId)){
            sObjectTypeName = sObjectId.getSobjectType().getDescribe().getName();
        }

        Known_Issue__c newKi = new Known_Issue__c();

        if(!String.isBlank(sObjectTypeName)){
            newKi.Record_Detail_Id__c = sObjectId;
            newKi.Object_List_ObjectName__c = sObjectTypeName;

            if(sObjectTypeName == 'Dashboard' || sObjectTypeName == 'Report'){
                newKi.Dashboard_Report_Id__c = sObjectId;
            }
            else if(sObjectTypeName == 'ContentDocument'){
                newKi.Document_Id__c = sObjectId;
            }
            else if(sObjectTypeName == 'EmailTemplate'){
                newKi.Email_Template_Id__c = sObjectId;
            }
        }

        newKi.Message__c = edm.get(0).Message__c;
        newKi.Message_Summary__c = edm.get(0).Message__c;
        newKi.Einstein_Keyword__c = EinsteinUtils.getUndefinedKeywordId();
        newKi.Status__c = 'Pending Approval';
        newKi.Priority__c = 'Normal (3)';
        
        if(contentVersion != null){
            newKi.Content_Document__c = contentVersion.Id;
        }

        insert newKi;

        EinsteinUtils.associateMessageWithIssue(edm.get(0).Id, newKi.Id);

        return newKi;
    }


    // Will return a list of Known Issues that were approved by an admin and match the target's Name or Id
    // Also returns the list of Subscribers. List<Known_Issue_Subscriber__c> subscribers = issue.Known_Issue_Subscribers__r;
    public static List<Known_Issue__c> getKnownIssues(Id recordTypeId, String targetName, String targetId) {

        if (String.isBlank(targetName) && String.isBlank(targetId)) {
            return new List<Known_Issue__c>();
        }

        String soqlQuery = 'SELECT Id,'
                                 + 'Name,'
                                 + 'CreatedById,'
                                 + 'CreatedBy.Name,'
                                 + 'CreatedDate,'
                                 + 'Estimated_Due_Date__c,'
                                 + 'RecordTypeId,'
                                 + 'RecordType.Name,'
                                 + 'Status__c,'
                                 + 'Priority__c,'
                                 + 'Related_Issue__c,'
                                 + 'Einstein_Keyword__c,'
                                 + 'Message__c,'
                                 + 'Message_Summary__c,'
                                 + 'Reason__c,'
                                 + 'Dashboard_Report_Id__c,'
                                 + 'Document_Id__c,'
                                 + 'Email_Template_Id__c,'
                                 + 'Object_List_ObjectName__c,'
                                 + 'Package_Name__c,'
                                 + 'Record_Detail_Id__c,'
                                 + 'Visualforce_Page_Name__c,'
                                 + '(SELECT Id, Known_Issue__c, Subscriber__c, Subscriber__r.Name FROM Known_Issue_Subscribers__r)'
        				 + ' FROM Known_Issue__c'
        				 + ' WHERE ( (Dashboard_Report_Id__c != null AND Dashboard_Report_Id__c = :targetId)'
                                 + ' OR (Document_Id__c != null AND Document_Id__c = :targetId)'
                                 + ' OR (Email_Template_Id__c != null AND Email_Template_Id__c = :targetId)'
                                 + ' OR (Object_List_ObjectName__c != null AND Object_List_ObjectName__c = :targetName)'
                                 + ' OR (Package_Name__c != null AND Package_Name__c = :targetName)'
                                 + ' OR (Record_Detail_Id__c != null AND Record_Detail_Id__c = :targetId)'
                                 + ' OR (Visualforce_Page_Name__c != null AND Visualforce_Page_Name__c = :targetName) )'
        				 + ( String.isNotBlank(recordTypeId) ? ' AND RecordTypeId = :recordTypeId' : '' )
            			 + ' AND Status__c = :STATUS_NEW'
            			 + ' AND Message_Summary__c != null';

        return Database.query(soqlQuery);
    }

    public static Boolean verifyUserIsSubscribed(Id issueId, Id userId) {
        List<Known_Issue_Subscriber__c> subscribers = [ SELECT Id FROM Known_Issue_Subscriber__c
                                                        WHERE Known_Issue__c = :issueId
                                                        AND Subscriber__c = :userId ];
        return !subscribers.isEmpty();
    }

    public static void subscribeUsersToIssue(Id issueId, List<Id> userIds) {
        List<Known_Issue_Subscriber__c> subscribers = new List<Known_Issue_Subscriber__c>();
        for(Id userId: userIds){
            subscribers.add( new Known_Issue_Subscriber__c(Known_Issue__c = issueId,
                                                          	Subscriber__c  = userId));
        }
        if (!subscribers.isEmpty()) {
            insert subscribers;
        }
    }

    public static void removeSubscribers(Id issueId, List<Id> userIds) {
        List<Known_Issue_Subscriber__c> subscribers = [ SELECT Id FROM Known_Issue_Subscriber__c
                                                        WHERE Known_Issue__c = :issueId
                                                        AND Subscriber__c IN :userIds ];
        if (!subscribers.isEmpty()) {
           delete subscribers;
        }
    }


    public static void reparentSubscribersOfDuplicatedIssues(List<Known_Issue__c> issues) {
        Map<Id, Set<Id>> subUserIdsByOriginalIssueId = new Map<Id, Set<Id>>();
        for (Known_Issue__c issue: issues) {
            if (issue.Related_Issue__c != null)
        	subUserIdsByOriginalIssueId.put(issue.Related_Issue__c, new Set<Id>());
        }

        List<Known_Issue_Subscriber__c> subscribers = [ SELECT Id,
                                                       		   Known_Issue__c,
                                                       		   Known_Issue__r.Status__c,
                                                       		   Known_Issue__r.Related_Issue__c,
                                                       		   Subscriber__c
                                                       	FROM Known_Issue_Subscriber__c
                                                      	WHERE ( Known_Issue__c IN :issues
                                                      			AND Known_Issue__r.Related_Issue__c != null
                                                              	AND Known_Issue__r.Status__c = :STATUS_DUPLICATED )
                                                      	OR Known_Issue__c IN :subUserIdsByOriginalIssueId.keySet() ];

		for (Known_Issue_Subscriber__c sub: subscribers) {
            if ( subUserIdsByOriginalIssueId.containsKey(sub.Known_Issue__c) ) {
            	subUserIdsByOriginalIssueId.get(sub.Known_Issue__c).add(sub.Subscriber__c);
            }
        }

        List<Known_Issue_Subscriber__c> subsToUpdate = new List<Known_Issue_Subscriber__c>();
        List<Known_Issue_Subscriber__c> subsToDelete = new List<Known_Issue_Subscriber__c>();
        for (Known_Issue_Subscriber__c sub: subscribers) {
            if ( sub.Known_Issue__r.Status__c == STATUS_DUPLICATED ) {
                Set<Id> usersSubscribedToOriginalIssue = subUserIdsByOriginalIssueId.get(sub.Known_Issue__r.Related_Issue__c);
                if (usersSubscribedToOriginalIssue != null && usersSubscribedToOriginalIssue.contains(sub.Subscriber__c) ) {
                    subsToDelete.add(sub);
                } else {
                    sub.Known_Issue__c = sub.Known_Issue__r.Related_Issue__c;
                    subsToUpdate.add(sub);
                }
            }
        }

        if (!subsToUpdate.isEmpty()) {
            update subsToUpdate;
        }
        if (!subsToDelete.isEmpty()) {
            delete subsToDelete;
        }
    }


    public static void notifyFixedIssuesSubscribers(List<Known_Issue__c> issues, Map<Id,Known_Issue__c> oldIssuesById) {

        Set<Id> fixedIssues = new Set<Id>();
        for (Known_Issue__c issue : issues) {
            if ( issue.Status__c == STATUS_FIXED
                	&& issue.Status__c != oldIssuesById.get(issue.Id).Status__c ) {
                fixedIssues.add(issue.Id);
            }
        }

        if (fixedIssues.isEmpty()) {
            return;
        }

        List<Known_Issue_Subscriber__c> subscribers = [ SELECT Id,
                                                       		   Known_Issue__c,
                                                       		   Known_Issue__r.Name,
                                                       		   Known_Issue__r.Message_Summary__c,
                                                       		   Subscriber__c
                                                       	FROM Known_Issue_Subscriber__c
                                                      	WHERE Known_Issue__c IN :fixedIssues ];

        // prepare Platform Events and Emails
        List<Bot_Notification__e > botNotifications = new List<Bot_Notification__e >();
        List<Messaging.SingleEmailMessage> botNotificationEmails = new List<Messaging.SingleEmailMessage>();

        for (Known_Issue_Subscriber__c sub: subscribers) {

            // create a bot notification per subscriber
            botNotifications.add( GeneralUtils.getNewBotNotification( sub.Known_Issue__c,
																	  sub.Known_Issue__r.Name,
																	  sub.Known_Issue__r.Message_Summary__c,
																	  sub.Subscriber__c ) );
            // create email noification
            botNotificationEmails.add( GeneralUtils.getNewBotNotificationEmail( sub.Known_Issue__c,
																				sub.Known_Issue__r.Name,
																				sub.Known_Issue__r.Message_Summary__c,
																				sub.Subscriber__c ) );
        }

        // publish bot notifications
        List<Database.SaveResult> results = EventBus.publish(botNotifications);

        // send email notifications
        Messaging.sendEmail(botNotificationEmails);

    }


    public static List<Known_Issue__c> setUndefinedKeyword(List<Known_Issue__c> issues) {
        Id undefinedKeywordId = EinsteinUtils.getUndefinedKeywordId();
        for (Known_Issue__c issue: issues) {
            if (issue.Einstein_Keyword__c == null) {
                issue.Einstein_Keyword__c = undefinedKeywordId;
            }
        }
        return issues;
    }

    public static void setDuplicatedOrNewKeyword(List<Known_Issue__c> issuesToUpdate, Map<Id,Known_Issue__c> oldIssuesById){
        for(Known_Issue__c updatedKI: issuesToUpdate){
            if(updatedKI.Status__c == oldIssuesById.get(updatedKI.Id).Status__c && updatedKI.Status__c != null){
                if(updatedKI.Einstein_Keyword__c != null){
                    Einstein_Keyword__c issueKeyword = [Select id, Name
                                                        FROM Einstein_Keyword__c
                                                        WHERE ID = :updatedKI.Einstein_Keyword__c
                                                        Limit 1];
                    if(issueKeyword.Id != EinsteinUtils.getUndefinedKeywordId()){

                            List<Known_Issue__c> duplicatedKnownIssues = [SELECT Id, Einstein_Keyword__r.Name
                                                                          FROM Known_Issue__c
                                                                          WHERE Id != :updatedKI.Id
                                                                          AND Einstein_Keyword__r.Name = :issueKeyword.Name];
                            if(duplicatedKnownIssues.size() > 0){
                                updatedKI.Status__c = STATUS_DUPLICATED;
                            }else{
                                updatedKI.Status__c = STATUS_NEW;
                            }
                    }

                }
            }
        }
    }
}