Bot_V2/src/objects/Bot_Notification__e.object
<CustomObject>
    <fields>
        <fullName>Known_Issue_Id__c</fullName>
        <label>Known_Issue_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Known_Issue_Name__c</fullName>
        <label>Known_Issue_Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Known_Issue_Subscriber__c</fullName>
        <label>Known_Issue_Subscriber</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Known_Issue_Summary__c</fullName>
        <label>Known_Issue_Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bot Notification</label>
    <pluralLabel>Bot Notifications</pluralLabel>
</CustomObject>

Bot_V2/src/objects/Known_Issue_Subscriber__c.object
<CustomObject>
    <label>Known Issue Subscriber</label>
    <nameField>
        <label>Known Issue Subscriber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Known Issue Subscribers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bot_V2/src/classes/GeneralUtils.cls
public class GeneralUtils {
	
    public static final EmailTemplate EMAILTEMPLATE_BOTNOTIFICATION = [ SELECT Body, HtmlValue, Subject FROM EmailTemplate WHERE DeveloperName = 'Bot_Notification' ];
    
    public static Bot_Notification__e getNewBotNotification(Id issueId, String issueName, String issueSummary, String issueSubscriberId) {
        return new Bot_Notification__e( Known_Issue_Id__c = issueId,
                                        Known_Issue_Name__c  = issueName,
                                        Known_Issue_Summary__c = issueSummary,
                                        Known_Issue_Subscriber__c = issueSubscriberId );
    }
    
    
    public static Messaging.SingleEmailMessage getNewBotNotificationEmail(Id issueId, String issueName, String issueSummary, String issueSubscriberId) {
        return getNewEmailMesage( new String[]{issueSubscriberId},
								  String.format( EMAILTEMPLATE_BOTNOTIFICATION.Subject, new String[]{issueName} ),
								  String.format( EMAILTEMPLATE_BOTNOTIFICATION.Body, new String[]{issueName, issueSummary} ),
								  String.format( EMAILTEMPLATE_BOTNOTIFICATION.HtmlValue, new String[]{issueName, issueSummary} ) );
    }
    
    
    public static Messaging.SingleEmailMessage getNewEmailMesage(String[] toAddresses, String subject, String plainTextBody,  String htmlBody) {
        
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
		
        message.toAddresses = toAddresses;
        message.subject = subject;
        if (String.isNotBlank(plainTextBody)) {
            message.setPlainTextBody(plainTextBody);
        }
        if (String.isNotBlank(htmlBody)) {
            message.setHtmlBody(htmlBody);
        }
		
        return message;
        
    }
    
}