Bot_V2/src/objects/Einstein_Data_Message__c.object
<CustomObject>
    <fields>
        <fullName>Einstein_Keyword__c</fullName>
        <label>Einstein Keyword</label>
        <referenceTo>Einstein_Keyword__c</referenceTo>
        <relationshipLabel>Einstein Data Messages</relationshipLabel>
        <relationshipName>Einstein_Data_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Einstein Data Message</label>
    <nameField>
        <displayFormat>EDM-{0000}</displayFormat>
        <label>Einstein Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Einstein Data Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bot_V2/src/objects/Einstein_Keyword__c.object
<CustomObject>
    <label>Einstein Keyword</label>
    <nameField>
        <label>Einstein Keyword Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Keywords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot_V2/src/classes/EinsteinUtilsTest.cls
@isTest
public class EinsteinUtilsTest {
	
    static testmethod void testEinsteinEnabled() {
        
        Test.startTest();
        
        Boolean einsteinDisabled = EinsteinUtils.getEinsteinEnabled();
        EinsteinUtils.setEinsteinEnabled(true);
        Boolean einsteinEnabled = EinsteinUtils.getEinsteinEnabled();
        
        Test.stopTest();
        
        System.assertEquals(false, einsteinDisabled, 'Einstein should start disabled');
        System.assertEquals(true, einsteinEnabled, 'Einstein should have been enabled');
    }    
    
    static testmethod void testCreateMessage() {
        
        Einstein_Keyword__c keywordTest = new Einstein_Keyword__c(Name = 'TEST');
        insert keywordTest;
        
        Test.startTest();
        
        Id messageUndefinedId = EinsteinUtils.createMessage(null, 'TESTABC');
        Id messageDefinedId = EinsteinUtils.createMessage(keywordTest.Id, 'TEST123');
        Id undefinedKeywordId = EinsteinUtils.getUndefinedKeywordId();
        
        Test.stopTest();
		
        List<Einstein_Data_Message__c> messages = [ SELECT Id, Einstein_Keyword__c FROM Einstein_Data_Message__c WHERE Id = :messageUndefinedId OR Id = :messageDefinedId ORDER BY CreatedDate ];
        System.assertEquals(2, messages.size(), 'Two messages should have been created');
        System.assertEquals(undefinedKeywordId, messages[0].Einstein_Keyword__c, 'Message should be assigned to undefined keyword');
        System.assertEquals(keywordTest.Id, messages[1].Einstein_Keyword__c, 'Message should be assigned to test keyword');
    }
    
        
}