Bot_V2/src/objects/Einstein_Data_Message__c.object
<CustomObject>
    <fields>
        <fullName>Einstein_Keyword__c</fullName>
        <label>Einstein Keyword</label>
        <referenceTo>Einstein_Keyword__c</referenceTo>
        <relationshipLabel>Einstein Data Messages</relationshipLabel>
        <relationshipName>Einstein_Data_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Einstein_Upload_Status__c</fullName>
        <label>Einstein_Upload_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Uploaded</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Known_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Known Issue</label>
        <referenceTo>Known_Issue__c</referenceTo>
        <relationshipLabel>Einstein Data Messages</relationshipLabel>
        <relationshipName>Einstein_Data_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <label>Einstein Data Message</label>
    <nameField>
        <displayFormat>EDM-{0000}</displayFormat>
        <label>Einstein Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Einstein Data Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bot_V2/src/objects/Einstein_Keyword__c.object
<CustomObject>
    <label>Einstein Keyword</label>
    <nameField>
        <label>Einstein Keyword Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Keywords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot_V2/src/objects/Known_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Einstein_Keyword__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einstein Keyword</label>
        <referenceTo>Einstein_Keyword__c</referenceTo>
        <relationshipLabel>Known Issues</relationshipLabel>
        <relationshipName>Known_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>The message as provided by the user.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Duplicated</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  
    <label>Known Issue</label>
    <nameField>
        <displayFormat>KI-{0000}</displayFormat>
        <label>Known Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot_V2/src/classes/checkEinsteinAvailableTEST.cls
@isTest
public class checkEinsteinAvailableTEST {
    
    @testSetup 
    static void methodName() {
        
        
        
        List<Einstein_Keyword__c> keywords = new List<Einstein_Keyword__c>();
        List<Known_Issue__c> knownIssues = new List<Known_Issue__c>();        
        List<Einstein_Data_Message__c> messages = new List<Einstein_Data_Message__c>();
        
        for(Integer i=0; i<3; i++) {
            Einstein_Keyword__c keyword = new Einstein_Keyword__c(
                Name = 'TEST KEYWORD ' + String.valueOf(i+1),
                Einstein_Upload_Status__c = EinsteinUtils.UPLOAD_STATUS_NOT_UPLOADED
            );
            keywords.add(keyword);
        }      
        insert keywords;
        
        for (Einstein_Keyword__c keyword: keywords) {
            // Create Known Issue
            knownIssues.add(new Known_Issue__c(
                Einstein_Keyword__c = keyword.Id,
                Status__c = EinsteinUtils.KNOWN_ISSUE_NEW,
                Message__c = 'Problem with ' + keyword.Name
            ));            
            for(Integer i=0; i<5; i++) {
                messages.add(new Einstein_Data_Message__c(
                    Einstein_Keyword__c = keyword.Id,
                    Message__c = 'TEST MESSAGE ' + String.valueOf(i+1),
                    Einstein_Upload_Status__c = EinsteinUtils.UPLOAD_STATUS_NOT_UPLOADED
                ));
            }
        }
        insert knownIssues;
        insert messages;
        
        
        set<ID> ids = new set<ID>();
        for(Einstein_Keyword__c i: keywords){
            
            ids.add(i.Id);
        }
       // EinsteinUtils.uploadMessagesToEinstein(ids);
       // EinsteinUtils.setEinsteinDatasetId(1009954);
       // EinsteinUtils.setEinsteinModelId('IKAJAIQPM5IG7E5CDI6WMKK6NI');
        
    }
    
    static testmethod void testEinsteinAvailable(){
        boolean before = EinsteinUtils.getEinsteinEnabled();    
        Test.startTest();
        checkEinsteinAvailable cEA = new checkEinsteinAvailable();
        Database.executeBatch(cEA);     
        Test.stopTest();
        boolean after = EinsteinUtils.getEinsteinEnabled();
        system.assertEquals(after, before);
    }
    
}