Bot_V2/src/objects/Known_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Dashboard_Report_Id__c</fullName>
        <label>Dashboard/Report Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Id__c</fullName>
        <label>Document Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Template_Id__c</fullName>
        <label>Email Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Summary__c</fullName>
        <inlineHelpText>The message simplified by the Admin.</inlineHelpText>
        <label>Message Summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>The message as provided by the user.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_List_ObjectName__c</fullName>
        <label>Object List ObjectName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Detail_Id__c</fullName>
        <label>Record Detail Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Duplicated</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visualforce_Page_Name__c</fullName>
        <label>Visualforce Page Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
  
    <label>Known Issue</label>
    <nameField>
        <displayFormat>KI-{0000}</displayFormat>
        <label>Known Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bot_V2/src/objects/Known_Issue_Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Known_Issue__c</fullName>
        <label>Known Issue</label>
        <referenceTo>Known_Issue__c</referenceTo>
        <relationshipLabel>Known Issue Subscribers</relationshipLabel>
        <relationshipName>Known_Issue_Subscribers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriber</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Known_Issue_Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Known Issue Subscriber</label>
    <nameField>
        <label>Known Issue Subscriber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Known Issue Subscribers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bot_V2/src/classes/KnownIssuesUtilsTest.cls
@isTest
public class KnownIssuesUtilsTest {

    static testmethod void testGetKnownIssues() {
        
        List<Known_Issue__c> issues = new List<Known_Issue__c>();
        String targetId = 'a01f400000AAAAA123';
        String targetName = 'nameABC';
        for(Integer i=0; i<10; i++){
        	issues.add( getNewKnownIssue('message', 'summary', KnownIssuesUtils.STATUS_NEW, targetName, targetId ) );
        }
        issues[0].recordTypeId = KnownIssuesUtils.RTYPE_ID_VFP;
        insert issues;
        
        Test.startTest();
        
        List<Known_Issue__c> emptyList = KnownIssuesUtils.getKnownIssues(null, null, null);
        
        List<Known_Issue__c> fullList = KnownIssuesUtils.getKnownIssues(null, targetName, targetId );
        Integer fullListSize = KnownIssuesUtils.getKnownIssuesCount(null, targetName, targetId);
        
        List<Known_Issue__c> recordTypeFilteredList = KnownIssuesUtils.getKnownIssues(KnownIssuesUtils.RTYPE_ID_VFP, targetName, targetId);
        Integer recordTypeFilteredListSize = KnownIssuesUtils.getKnownIssuesCount(KnownIssuesUtils.RTYPE_ID_VFP, targetName, targetId);
        
        Test.stopTest();
        
        System.assertEquals(0, emptyList.size(), 'emptyList search should return 0 issues.');
        System.assertEquals(10, fullList.size(), 'fullList search should return 10 issues.');
        System.assertEquals(fullList.size(), fullListSize, 'fullList and fullListSize mismatch.');
        System.assertEquals(1, recordTypeFilteredList.size(), 'recordTypeFilteredList search should return 1 issue.');
        System.assertEquals(recordTypeFilteredList.size(), recordTypeFilteredListSize, 'recordTypeFilteredListSize and recordTypeFilteredListSize mismatch.');
        
    }
	
    
    static testmethod void testSubscribeUsersToIssue() {
        
        String targetId = 'a01f400000AAAAA123';
        String targetName = 'nameABC';
        Known_Issue__c issue = getNewKnownIssue('message', 'summary', KnownIssuesUtils.STATUS_NEW, targetName, targetId );
        insert issue;
        
        Test.startTest();
        
        KnownIssuesUtils.subscribeUsersToIssue(issue.Id, new List<Id>{UserInfo.getUserId()} );
        
        Test.stopTest();
        
        List<Known_Issue__c> issuesList = KnownIssuesUtils.getKnownIssues(null, targetName, targetId );
        System.assert(!issuesList.isEmpty() && !issuesList[0].Known_Issue_Subscribers__r.isEmpty(), 'No subscribers found for this issue.');
        System.assertEquals(UserInfo.getUserId(), issuesList[0].Known_Issue_Subscribers__r[0].Subscriber__c, 'Active user should be subscribed to the issue.');
        
    } 
    
    
    public static Known_Issue__c getNewKnownIssue(String message, String summary, String status, String targetName, String targetId ) {
        return new Known_Issue__c( Message__c = message,
                                   Message_Summary__c = summary,
                                   Status__c = KnownIssuesUtils.STATUS_NEW,
                                   Dashboard_Report_Id__c = targetId,
                                   Document_Id__c = targetId,
                                   Email_Template_Id__c = targetId,
                                   Object_List_ObjectName__c = targetName,
                                   Package_Name__c = targetName,
                                   Record_Detail_Id__c = targetId,
                                   Visualforce_Page_Name__c = targetName );
    }
}